# Generated by Django 6.1.1 on 2026-10-08 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatchAllocationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(max_length=20)),
                ('allocated_qty', models.FloatField(default=0)),
                ('batch_time_hours', models.FloatField(default=0)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('running', 'Running'), ('completed', 'Completed')], default='planned', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Batch Allocation Detail',
                'verbose_name_plural': 'Batch Allocation Details',
                'ordering': ['order', 'batch_id'],
            },
        ),
        migrations.CreateModel(
            name='DyeingMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(choices=[('EAL', 'EAL'), ('Others', 'Others')], default='EAL', help_text='Company name (e.g., EAL)', max_length=50)),
                ('machine_capacity', models.CharField(help_text='e.g., 3000X1, 2800X1, 7X6', max_length=100)),
                ('cone', models.FloatField(default=0, help_text='Cone value (kg)')),
                ('knit_sweater_min', models.FloatField(default=0)),
                ('knit_sweater_max', models.FloatField(default=0)),
                ('knit_yarn_min', models.FloatField(default=0)),
                ('knit_yarn_max', models.FloatField(default=0)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dyeing Machine',
                'verbose_name_plural': 'Dyeing Machines',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('order_date', models.DateField()),
                ('ref_no_buyers', models.CharField(blank=True, max_length=200, null=True)),
                ('work_order_remark', models.CharField(blank=True, max_length=300, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('yarn_count', models.CharField(max_length=100)),
                ('yarn_code', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('approval', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3)),
                ('order_qty', models.FloatField(default=0)),
                ('party_yarn', models.FloatField(default=0)),
                ('store_yarn', models.FloatField(default=0)),
                ('add_percent_yn', models.FloatField(default=0)),
                ('dyeing_qty', models.FloatField(default=0)),
                ('reject_qty', models.FloatField(default=0)),
                ('dyed_bal_qty', models.FloatField(default=0)),
                ('finish_qty', models.FloatField(default=0)),
                ('del_qty', models.FloatField(default=0)),
                ('held_up_qty', models.FloatField(default=0)),
                ('delivery_return', models.FloatField(default=0)),
                ('delivery_qty', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('Inactive', 'Inactive'), ('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Delayed', 'Delayed'), ('Emergency', 'Emergency')], default='Pending', max_length=30)),
                ('priority', models.CharField(choices=[('Normal', 'Normal'), ('Emergency', 'Emergency'), ('High', 'High'), ('Low', 'Low')], default='Normal', max_length=20)),
                ('is_planned', models.BooleanField(default=False)),
                ('current_step', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('plan_type', models.CharField(choices=[('auto', 'Auto'), ('manual', 'Manual')], default='auto', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Production Plan',
                'verbose_name_plural': 'Production Plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BatchProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_step', models.CharField(choices=[('Store', 'Store'), ('Soft winding', 'Soft winding'), ('Dyeing', 'Dyeing'), ('Hydro', 'Hydro'), ('Dryer', 'Dryer'), ('Quality check', 'Quality check'), ('Finishing', 'Finishing'), ('Packing', 'Packing'), ('Store (Final)', 'Store (Final)'), ('Delivery', 'Delivery'), ('Completed', 'Completed')], default='Store', max_length=50)),
                ('completed_steps', models.JSONField(blank=True, default=list)),
                ('step_timestamps', models.JSONField(blank=True, default=dict)),
                ('comment', models.TextField(blank=True, null=True)),
                ('delivery_issue', models.JSONField(blank=True, default=dict, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_rejection_reallocated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='process_tracker', to='dpms_app.batchallocationdetail')),
            ],
            options={
                'verbose_name': 'Batch Process',
                'verbose_name_plural': 'Batch Processes',
            },
        ),
        migrations.AddField(
            model_name='batchallocationdetail',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_details', to='dpms_app.dyeingmachine'),
        ),
        migrations.AddField(
            model_name='batchallocationdetail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_details', to='dpms_app.order'),
        ),
        migrations.CreateModel(
            name='BatchAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('is_allocated', models.BooleanField(default=False)),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocations', to='dpms_app.dyeingmachine')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='batch_allocation', to='dpms_app.order')),
            ],
            options={
                'verbose_name': 'Batch Allocation',
                'verbose_name_plural': 'Batch Allocations',
            },
        ),
        migrations.CreateModel(
            name='PlanStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name', models.CharField(max_length=100)),
                ('step_order', models.PositiveIntegerField(default=0)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration_hours', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_steps', to='dpms_app.dyeingmachine')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_steps', to='dpms_app.order')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='dpms_app.productionplan')),
            ],
            options={
                'verbose_name': 'Plan Step',
                'verbose_name_plural': 'Plan Steps',
                'ordering': ['plan', 'order', 'step_order'],
            },
        ),
        migrations.CreateModel(
            name='Rejection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(max_length=100)),
                ('reason', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('batch_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejections', to='dpms_app.batchprocess')),
            ],
            options={
                'verbose_name': 'Rejection',
                'verbose_name_plural': 'Rejections',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='batchallocationdetail',
            unique_together={('order', 'batch_id')},
        ),
        migrations.CreateModel(
            name='StepComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name', models.CharField(max_length=100)),
                ('comment', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_comments', to='dpms_app.order')),
            ],
            options={
                'verbose_name': 'Step Comment',
                'verbose_name_plural': 'Step Comments',
                'unique_together': {('order', 'step_name')},
            },
        ),
    ]
