# Generated by Django 6.1.1 on 2026-10-01 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('order_date', models.DateField()),
                ('ref_no_buyers', models.CharField(blank=True, max_length=200, null=True)),
                ('work_order_remark', models.CharField(blank=True, max_length=300, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('yarn_count', models.CharField(max_length=100)),
                ('yarn_code', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('approval', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3)),
                ('order_qty', models.FloatField(default=0)),
                ('party_yarn', models.FloatField(default=0)),
                ('store_yarn', models.FloatField(default=0)),
                ('add_percent_yn', models.FloatField(default=0)),
                ('dyeing_qty', models.FloatField(default=0)),
                ('reject_qty', models.FloatField(default=0)),
                ('dyed_bal_qty', models.FloatField(default=0)),
                ('finish_qty', models.FloatField(default=0)),
                ('del_qty', models.FloatField(default=0)),
                ('held_up_qty', models.FloatField(default=0)),
                ('delivery_return', models.FloatField(default=0)),
                ('delivery_qty', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('Inactive', 'Inactive'), ('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Delayed', 'Delayed'), ('Emergency', 'Emergency')], default='Pending', max_length=30)),
                ('priority', models.CharField(choices=[('Normal', 'Normal'), ('Emergency', 'Emergency'), ('High', 'High'), ('Low', 'Low')], default='Normal', max_length=20)),
                ('is_planned', models.BooleanField(default=False)),
                ('current_step', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
