# Generated by Django 6.1.1 on 2026-10-01 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpms_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DyeingMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(choices=[('EAL', 'EAL'), ('Others', 'Others')], default='EAL', help_text='Company name (e.g., EAL)', max_length=50)),
                ('machine_capacity', models.CharField(help_text='e.g., 3000X1, 2800X1, 7X6', max_length=100)),
                ('cone', models.FloatField(default=0, help_text='Cone value (kg)')),
                ('knit_sweater_min', models.FloatField(default=0, help_text='Knit Sweater Yarn Min (kg)')),
                ('knit_sweater_max', models.FloatField(default=0, help_text='Knit Sweater Yarn Max (kg)')),
                ('knit_yarn_min', models.FloatField(default=0, help_text='Knit Yarn Min (kg)')),
                ('knit_yarn_max', models.FloatField(default=0, help_text='Knit Yarn Max (kg)')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order e dekhate (choto number age)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dyeing Machine',
                'verbose_name_plural': 'Dyeing Machines',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
