# Generated by Django 6.1.1 on 2026-10-08 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpms_app', '0002_parameterfolder_parameter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parameter',
            options={'ordering': ['display_order', 'name'], 'verbose_name': 'Parameter', 'verbose_name_plural': 'Parameters'},
        ),
        migrations.AlterModelOptions(
            name='parameterfolder',
            options={'ordering': ['display_order', 'name'], 'verbose_name': 'Parameter Folder', 'verbose_name_plural': 'Parameter Folders'},
        ),
        migrations.AddField(
            model_name='parameterfolder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='value',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='parameterfolder',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='parameterfolder',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
