# Generated by Django 6.1.1 on 2026-10-08 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpms_app', '0003_alter_parameter_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManageStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('initial_time', models.FloatField(default=0, help_text='Initial time in hours')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Manage Step',
                'verbose_name_plural': 'Manage Steps',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
