# Generated by Django 6.1.1 on 2026-10-08 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpms_app', '0004_managestep'),
    ]

    operations = [
        migrations.AddField(
            model_name='managestep',
            name='break_time',
            field=models.FloatField(default=0, help_text='Break time (hours) after this step, before next step'),
        ),
    ]
