# Generated by Django 6.1.1 on 2026-10-08 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpms_app', '0006_order_delivery_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStepTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_trackers', to='dpms_app.order')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_trackers', to='dpms_app.managestep')),
            ],
            options={
                'verbose_name': 'Order Step Tracker',
                'verbose_name_plural': 'Order Step Trackers',
                'ordering': ['step__display_order', 'step__id'],
                'unique_together': {('order', 'step')},
            },
        ),
    ]
